pipeline {
    agent any

    environment {
        ANSIBLE_PLAYBOOK_PATH = '/etc/ansible/playbooks/frontend.yml'
        ANSIBLE_INVENTORY_PATH = '/etc/ansible/aws_ec2.yml'
    }

    stages {
        stage('Build and push image') {
            script {
                def front_image = docker.build("sebastianmontoyaz/rampup-perfi:frontend")
                front_image.push('latest')
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                ansiblePlaybook(
                    playbook: "${env.ANSIBLE_PLAYBOOK_PATH}",
                    inventory: "${env.ANSIBLE_INVENTORY_PATH}",
                    extras: '-e ilb=internal-SMZ-lb-internal-945498851.us-east-1.elb.amazonaws.com'
                )
            }
        }
    }
}